---
  - name: Manage CMS server
    hosts: [ 'cms', 'cms_stack' ]
    become: True
  
    environment: '{{ inventory__environment | d({})
                     | combine(inventory__group_environment | d({}))
                     | combine(inventory__host_environment  | d({})) }}'
  
    roles:
      - role: ../roles/common
        tags: [ 'role::common' ]

      - role: debops.ferm
        tags: [ 'role::ferm' ]
        ferm__dependent_rules:
          - '{{ mariadb_server__ferm__dependent_rules }}'
  
      - role: debops.tcpwrappers
        tags: [ 'role::tcpwrappers' ]
        tcpwrappers__dependent_allow:
          - '{{ mariadb_server__tcpwrappers__dependent_allow }}'
  
      - role: debops.mariadb_server
        tags: [ 'role::mariadb_server' ]

      - role: debops.mariadb
        tags: [ 'role::mariadb' ]

      - role: ../roles/cms
        tags: [ 'role::cromwell', 'role::mysql', 'role::slurm' ]